### ISSUE TITLE
an ffi question!

### ISSUE THREAD

**Issue by iomeone** [andyarvanitis/purescript-native-ffi#3]
Hi , sorry borther you again!
I want to use [purescript-unicode](https://github.com/purescript-contrib/purescript-unicode) package and fall into a bug , and tried lots of time , but can not solve it. 

my code is :
```
module Main where


import Prelude hiding (between,when)
import Data.Char.Unicode (digitToInt, isDigit)
import Effect (Effect)
import Effect.Console (logShow)

main :: Effect Unit
main = do
  logShow (isDigit '4')
```

it will call an ffi named toCharCode

so I wrote the ffi 

```
FOREIGN_BEGIN( Data_Enum )

// foreign import toCharCode :: Char -> Int
exports["toCharCode"] = [](const boxed& c_) -> boxed {
  int  c = unbox <char>(c_);
  return c;
};

FOREIGN_END
```

but it keeps crash again and again, I also tried 
```
const string  s = unbox<string>(c_);
const int  i = unbox<int>(c_);
```
but got no lucky！ crash as usual!

would you please point out what's wong with the code? 
thank you very much!
#

**Comment by andyarvanitis** [comment]
the changes for
```
exports["topChar"] = u8"\U0010FFFF"; // unicode limit
exports["bottomChar"] = u8"\0";
```
went in a while back, so not sure why I didn't close this then.
